apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erp_solution

resources:
  - ../../base

labels:
  - pairs:
      environment: production

replicas:
  - name: erp_solution-api
    count: 5
  - name: erp_solution-web
    count: 3
  - name: erp_solution-worker
    count: 3

images:
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-api
    newTag: v3.0.0
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-web
    newTag: v3.0.0
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-worker
    newTag: v3.0.0
