apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - migrate-job.yaml
  - external-secret.yaml
  - servicemonitor.yaml
  - alert-rules.yaml
images:
  - name: ghcr.io/nyeinpyaesone-ui/erp03-erpnext
    newTag: IMAGE_TAG
