apiVersion: batch/v1
kind: Job
metadata:
  generateName: erpnext-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: erpnext-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/nyeinpyaesone-ui/erp03-erpnext:IMAGE_TAG
          command: ["bench", "migrate"]
          envFrom:
            - secretRef:
                name: erpnext-secrets
