apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erp_solution

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - network-policy.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - ollama.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: erp_solution
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-api
    newTag: v3.0.0
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-web
    newTag: v3.0.0
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-worker
    newTag: v3.0.0
  - name: postgres
    newTag: 15.8-alpine
  - name: redis
    newTag: 7.2.4-alpine
  - name: ollama/ollama
    newTag: 0.3.9
  - name: nginx
    newTag: 1.29-alpine

