apiVersion: v1
kind: Namespace
metadata:
  name: erpo3
  labels:
    app.kubernetes.io/name: erpo3
    app.kubernetes.io/part-of: erpo3-system
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: erpo3-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: erpo3-system

