apiVersion: v1
kind: Namespace
metadata:
  name: erp03
  labels:
    app.kubernetes.io/name: erp03
    app.kubernetes.io/part-of: erp03-system
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: erp03-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: erp03-system

