apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erpo3-uploads
  namespace: erpo3
  labels:
    app.kubernetes.io/name: erpo3
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: erpo3
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi

