apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erp03-uploads
  namespace: erp03
  labels:
    app.kubernetes.io/name: erp03
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: erp03
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi

