apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml

commonLabels:
  app.kubernetes.io/name: erp03
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: erp03-platform
