name: Container Build Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Build ERP backend image
        run: docker build ./ERP-BACKEND -f ./ERP-BACKEND/Dockerfile -t erp03-backend:ci

      - name: Build ERP frontend image
        run: docker build ./ERP-BACKEND/frontend-react -f ./ERP-BACKEND/frontend-react/Dockerfile -t erp03-frontend:ci
